version: "3.3" 
services:
  mysql:
    image: mariadb:10.5.6
    container_name: mariadb
    volumes:
      - ./backup:/backup
      - ./db_data:/var/lib/mysql
    ports:
      - '50006:3306'
    env_file:
      - database.env
